apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#namePrefix: sample-service-
#resources:
#  - ../../../base/kustomize

labels:
  - pairs:
      app: sample-service
    includeSelectors: true
    includeTemplates: true




