apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#namePrefix: dev-homepage-

resources:
  - ../../base


helmGlobals:
  chartHome: ../../../../base/charts
helmCharts:
  - name: flink-cluster
    releaseName: homepage-service-projector
    valuesFile: ../../base/common.values.yaml
    additionalValuesFiles:
      - values.yaml
