name: dev-homepage-service-projector
namespace: sn-dev-workload
image:
  name: docker-vtvgiaitri.vtvlive.vn/cellutions/seenow/homepage-service/projector
  tag: 12345678
  imagePullSecrets: regcred
job:
  jarURI: local:///opt/flink/examples/streaming/StateMachineExample.jar
  parallelism: 1
  upgradeMode: stateless
savepointBucket: argo-seenow-v2
checkpointBucket: argo-seenow-v2
flinkConfiguration:
  taskmanager.numberOfTaskSlots: "1"
  restart-strategy.type: failure-rate
  restart-strategy.failure-rate.max-failures-per-interval: "3"
  restart-strategy.failure-rate.failure-rate-interval: "5 min"
  restart-strategy.failure-rate.delay: "10 s"
  state.backend.type: hashmap
  execution.checkpointing.interval: "30 s"
  pipeline.max-parallelism: 64
  jobmanager.memory.flink.size: 512 mb
  taskmanager.memory.flink.size: 1 gb
  s3.access-key: 3QE5N275EGRCIZTKJC12
  s3.secret-key: nvuBdvt4Z0rcG9N1SheWhWhTmObuM1xBAgblkq4R
  s3.endpoint: s3.vtvlive.vn
#enableBuiltInPlugins:
#  - flink-s3-fs-presto
#  - flink-s3-fs-presto-1.17.2.jar
