apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  template:
    spec:
      containers:
        - name: main
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dev-sample-service-db-creds
                  key: postgresql-password
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: dev-shared-s3-sample-creds
                  key: access-key
